// server.dart
//
// Creates and configures the Serverpod Mini server for Kola.
//
// WHY Serverpod Mini (not full Serverpod)?
//   Full Serverpod manages its own Postgres connection pool via its ORM.
//   Kola uses Supabase for persistence instead (SRS.md §2), so we only need
//   the HTTP server, endpoint routing, and generated-client codegen — that's
//   exactly what Serverpod Mini provides. Every .spy.yaml model in this
//   project intentionally omits the `#table:` key for this reason: the
//   model's *shape* is generated by Serverpod, but its *storage* is handled
//   entirely by the DTO + Repository layer in lib/src/services/.
//
// TWO SEPARATE SERVERS, TWO SEPARATE PORTS (corrected — this used to say
// otherwise and it caused a real bug, see below):
//   Serverpod runs an `apiServer` (serves every generated Endpoint route —
//   this is what kola_client's Client actually POSTs to, e.g. `/workspace`)
//   and a `webServer` (Relic — serves only raw/custom routes registered via
//   pod.webServer.addRoute(...), e.g. the Telegram/WhatsApp webhook
//   receivers below). They are NOT the same server and Serverpod does not
//   currently support binding them to the same port. A generated endpoint
//   is unreachable on the webServer's port — hitting it there 404s with no
//   CORS headers (Relic's plain 404, not Serverpod's endpoint-dispatch
//   response), which is exactly what happened when this file only
//   overrode `webServer`'s port and kola_dashboard was poio answer `/workspace`. Fixed by overriding
//   `apiServer`'s port instead (see configOverride below) — that's the
//   one env-driven port kola_dashboard's KOLA_SERVER_URL should target.
//   webServer keeps Serverpod's own default port; it's only reached
//   directly by Telegram/WhatsApp via the public HTTPS webhookBaseUrl,
//   never by kola_dashboard.
//
// ADDING NEW ENDPOINTS:
//   1. Create a new file in lib/src/endpoints/
//   2. Extend Endpoint from serverpod
//   3. Run: dart run serverpod generate  (regenerates endpoints.dart/protocol.dart)
//   No manual registration needed — generate wires it in automatically.

import 'dart:async';
import 'dart:io';
import 'package:kola_server/src/generated/protocol.dart' hide Protocol;
import 'package:kola_server/src/generated/endpoints.dart';
import 'package:kola_server/web/api_routes.dart';
import 'package:serverpod/protocol.dart';
import 'package:serverpod/serverpod.dart';
import 'package:kola_server/src/config/env.dart';
import 'package:kola_server/src/services/repository/supabase_client.dart';
import 'package:kola_server/src/config/dependency_injection.dart';
import 'package:kola_server/src/services/security/channel_credential_encryption_service.dart';
import 'package:kola_server/src/services/messaging/telegram/telegram_bot_registry.dart';
import 'package:kola_server/src/services/messaging/whatsapp/whatsapp_bot_registry.dart';
import 'package:kola_server/src/services/messaging/channel_health_check_service.dart';
import 'package:kola_server/src/services/billing/paystack_webhook_route.dart';
import 'package:kola_server/src/services/billing/flutterwave_webhook_route.dart';
import 'package:kola_server/src/services/billing/kola_billing_paystack_webhook_route.dart';
import 'package:kola_server/src/services/billing/kola_billing_flutterwave_webhook_route.dart';
import 'package:kola_server/src/services/messaging/whatsapp/whatsapp_webhook_route.dart';
import 'package:kola_server/src/services/notifications/kola_notifier_bot.dart';
import 'package:kola_server/src/services/billing/trial_sweep_service.dart';
import 'package:kola_server/src/services/support/support_ticket_sla_sweep_service.dart';
import 'package:kola_server/src/services/support/customer_campaign_sweep_service.dart';
import 'package:kola_server/kola_logger.dart';
import 'package:logging/logging.dart' as logging;

/// Pipes the standard `logging` package into our Talker + Serverpod dual
/// logger, so any library that logs via `package:logging` (Supabase client
/// included) shows up in the same place as our own Log.* calls.
void setupLogging() {
  logging.Logger.root.level = logging.Level.ALL;
  logging.Logger.root.onRecord.listen((record) {
    if (record.level >= logging.Level.SEVERE) {
      Log.error(
        '${record.loggerName}: ${record.message}',
        error: record.error,
        stackTrace: record.stackTrace,
      );
    } else if (record.level >= logging.Level.WARNING) {
      Log.warning('${record.loggerName}: ${record.message}');
    } else if (record.level >= logging.Level.INFO) {
      Log.info('${record.loggerName}: ${record.message}');
    } else {
      Log.debug('${record.loggerName}: ${record.message}');
    }
  });
}

/// The starting point of the Serverpod server.
void run(List<String> args) async {
  setupLogging();
  Log.startup('Kola server is booting up...');

  try {
    // 1. Persistence — Supabase must be ready before any endpoint that
    //    touches a repository can be called.
    Log.startupInfo('Connecting to Supabase database...');
    await initSupabase();
    Log.startupSuccess('Database client ready');

    // 1b. Repositories (and, from later phases, services) — see
    //     dependency_injection.dart for what's registered.
    setupDependencyInjection();

    // 1c. Channel credential encryption — must be ready before
    //     TelegramBotRegistry.bootstrapFromDb() tries to decrypt any
    //     stored bot token, and before ChannelEndpoint can encrypt a new
    //     one. Same AES-256-GCM approach as Degenbot's wallet encryption
    //     (see channel_credential_encryption_service.dart).
    if (Env.channelCredentialMasterKey.isNotEmpty) {
      ChannelCredentialEncryptionService.init(Env.channelCredentialMasterKey);
      Log.startupSuccess('Channel credential encryption initialized');
    } else {
      Log.startupWarning(
        'CHANNEL_CREDENTIAL_MASTER_KEY not set — connecting a Telegram '
        'channel will fail until it is. See .env.example.',
      );
    }

    // 1d. WhatsApp webhook verify token — only needed once a business
    //     actually configures a Callback URL in Meta's App Dashboard, but
    //     worth flagging early rather than failing silently on the first
    //     verification handshake. See whatsapp_webhook_route.dart.
    if (Env.whatsappWebhookVerifyToken.isEmpty) {
      Log.startupWarning(
        'WHATSAPP_WEBHOOK_VERIFY_TOKEN not set — the WhatsApp webhook '
        'verification handshake will fail until it is. See .env.example.',
      );
    }

    // 2. Serverpod Mini instance, wired to the generated Protocol/Endpoints.
    //    Port is env-driven (Env.serverPort) so the same build works
    //    locally and in a container where the platform assigns $PORT.
    Log.startupInfo('Configuring Serverpod instance...');
    final webPort =
        int.tryParse(Platform.environment['PORT'] ?? Env.serverPort) ?? 8080;

    final publicHost = 'https://p01--kola--hnnl8wyj78qp.code.run';
    
    // Env.webhookBaseUrl.isNotEmpty
    //     ? Uri.parse(Env.webhookBaseUrl).host
    //     : 'localhost';

    // Serverpod won't enable webServer at all unless it's given a config
    // (there's no config/development.yaml in this project — every setting
    // comes from configOverride below), and pod.webServer.addRoute(...) for
    // the Telegram/WhatsApp webhook routes further down requires it to
    // exist. It can't share apiServer's port (Serverpod doesn't support
    // that), so it gets its own, one above apiServer's.
    final webServerPort = webPort + 1;

    final pod = Serverpod(
      args,
      Protocol(),
      Endpoints(),
      // apiServer is what dispatches generated Endpoint calls
      // (createWorkspace, listMyWorkspaces, etc.) — this is the port
      // kola_dashboard's KOLA_SERVER_URL must point at. webServer only
      // carries the raw webhook routes registered below; nothing in
      // kola_dashboard ever calls it directly.
      configOverride: (config) => config.copyWith(
        apiServer: ServerConfig(
          port: webPort,
          publicScheme: 'https',
          publicHost: publicHost,
          publicPort: 443,
        ),
        webServer: ServerConfig(
          port: webServerPort,
          publicScheme: 'https',
          publicHost: publicHost,
          publicPort: 443,
        ),
      ),
    );

    // 2b. Wire TelegramBotRegistry to this pod's route-adding mechanism,
    //     then build every already-connected Telegram bot's
    //     TelegramService + webhook route — BEFORE pod.start(), so every
    //     route exists the moment the web server actually starts
    //     listening. This does NOT talk to Telegram's servers yet (see
    //     connectAll() below) — mirrors Degenbot's init()/connect() split.
    TelegramBotRegistry.instance.configure(
      addRoute: pod.webServer.addRoute,
      webhookBaseUrl: Env.webhookBaseUrl,
    );
    Log.startupInfo('Bootstrapping connected Telegram channels...');
    await TelegramBotRegistry.instance.bootstrapFromDb();

    // 2c. WhatsApp: every connected channel now gets its OWN webhook
    //     route (/webhooks/whatsapp/<channelId>, registered inside
    //     bootstrapFromDb() via configure() below) — same shape as
    //     Telegram's per-channel routes. The ORIGINAL shared route
    //     (/webhooks/whatsapp, no channelId) is kept registered too,
    //     deliberately: the first channel ever connected is still
    //     verified against that exact URL in Meta's dashboard, and
    //     re-doing that handshake for zero functional gain isn't worth
    //     the churn right now (see whatsapp_webhook_route.dart's header
    //     for the full "legacy mode" reasoning). Safe to remove this one
    //     line once every channel has migrated to its own per-channel
    //     URL. No connectAll() split needed here — nothing below talks
    //     to Meta's servers, it just decrypts stored credentials into
    //     memory (see whatsapp_bot_registry.dart's header on why
    //     WhatsApp has no bootstrap/connect phase split).
    pod.webServer.addRoute(WhatsAppWebhookRoute(), '/webhooks/whatsapp');
    WhatsAppBotRegistry.instance.configure(
      addRoute: pod.webServer.addRoute,
      webhookBaseUrl: Env.webhookBaseUrl,
    );
    Log.startupInfo('Bootstrapping connected WhatsApp channels...');
    await WhatsAppBotRegistry.instance.bootstrapFromDb();

    // ── Custom routes go here (Phase 2+) ────────────────────────────────
    // e.g. pod.webServer.addRoute(MetaWebhookRoute(), '/webhooks/meta');
    // (Telegram's per-channel routes are already added above, inside
    // bootstrapFromDb() — see telegram_bot_registry.dart. WhatsApp's one
    // shared route is added just above — see whatsapp_webhook_route.dart.)

    // Task #127 / Phase 8a — one shared route per gateway, across every
    // workspace (not per-workspace like Telegram/WhatsApp): a business's
    // Paystack/Flutterwave webhook URL is configured once in THEIR OWN
    // gateway dashboard, and payment_webhook_handler.dart already knows
    // how to look up which workspace a given event belongs to. See that
    // file's header for the full reasoning.
    pod.webServer.addRoute(PaystackWebhookRoute(), '/webhooks/paystack');
    pod.webServer.addRoute(FlutterwaveWebhookRoute(), '/webhooks/flutterwave');

    // Task #148 — Kola's OWN subscription billing webhooks, deliberately
    // separate paths from the two above (which are per-workspace
    // customer-payment webhooks) — see
    // kola_billing_paystack_webhook_route.dart's header for why these
    // can never share a route with those.
    pod.webServer.addRoute(KolaBillingPaystackWebhookRoute(), '/webhooks/kola-billing/paystack');
    pod.webServer.addRoute(KolaBillingFlutterwaveWebhookRoute(), '/webhooks/kola-billing/flutterwave');

    Log.startupSuccess('Starting Serverpod Mini server...');
    await pod.start();
    Log.startupSuccess('Kola server running on port $webPort');

    // 3. NOW connect every bootstrapped Telegram bot to Telegram's
    //    servers — webhook routes are already live and reachable, so
    //    it's safe to tell Telegram where to POST updates.
    Log.startupInfo('Connecting Telegram bots to Telegram servers...');
    await TelegramBotRegistry.instance.connectAll();
    Log.startupSuccess('Telegram bots connected');

    // 3b. Task #82 — nightly channel-credential health check (SRS.md
    //     §13). MUST run after both TelegramBotRegistry.connectAll() and
    //     WhatsAppBotRegistry.bootstrapFromDb() above — checkHealth()
    //     calls into each registry's in-memory _services map, and a
    //     channel that hasn't finished bootstrapping yet would be
    //     wrongly reported as unhealthy (see channel_health_check_
    //     service.dart's header). Runs once immediately (same "don't
    //     wait a full cycle to catch what broke while the server was
    //     down" reasoning as the trial sweep below), then every 24h —
    //     "nightly" per the spec's own wording, not hourly like the
    //     trial sweep, since a dead credential doesn't need sub-day
    //     detection the way an elapsed trial window benefits from.
    final channelHealthCheck = getIt<ChannelHealthCheckService>();
    Log.startupInfo('Running initial channel health check...');
    final flaggedNow = await channelHealthCheck.runOnce();
    Log.startupSuccess('Channel health check complete — $flaggedNow channel(s) flagged');
    Timer.periodic(const Duration(hours: 24), (_) async {
      try {
        final flagged = await channelHealthCheck.runOnce();
        if (flagged > 0) Log.info('Channel health check: $flagged channel(s) flagged unhealthy');
      } catch (e) {
        Log.error('Channel health check failed', error: e);
      }
    });
    
    // 4. Task #154 / Phase 8c — API status route, for kola_dashboard to poll 
    //and show a "server is down" banner if the server is unreachable. 
    //Returns a simple JSON payload with a timestamp and the number of channels 
    //flagged unhealthy in the last health check. See api_routes
    pod.webServer.addRoute(ApiStatusRoute(flagged: flaggedNow.toString()),     '/api/status');


    // 4. Kola's own Telegram bot for owner escalation notifications —
    //    long-polling (no route needed), safe to start any time after
    //    pod.start(), same reasoning as any other long-polling Telegram
    //    bot. See kola_notifier_bot.dart's header.
    Log.startupInfo('Starting Kola notifier Telegram bot...');
    await KolaNotifierBot.instance.start();

    // 5. Phase 5b — trial sweep. Runs once immediately (so a workspace
    //    whose 14-day window elapsed while the server was stopped gets
    //    paused right away, not only after the next hour ticks over),
    //    then on a fixed interval for as long as this process lives.
    //    See trial_sweep_service.dart's header for why this is a plain
    //    Timer rather than a Serverpod FutureCall.
    final trialSweep = getIt<TrialSweepService>();
    Log.startupInfo('Running initial trial sweep...');
    final pausedNow = await trialSweep.sweepOnce();
    Log.startupSuccess('Trial sweep complete — $pausedNow workspace(s) paused');
    Timer.periodic(const Duration(hours: 1), (_) async {
      try {
        final paused = await trialSweep.sweepOnce();
        if (paused > 0) Log.info('Trial sweep: $paused workspace(s) paused');
      } catch (e) {
        Log.error('Trial sweep failed', error: e);
      }
    });

    // 6. Task #130 / Phase 8b — support ticket SLA-breach sweep. Same
    //    "run once immediately, then on a fixed interval" shape as the
    //    trial sweep above, and the same plain-Timer reasoning (no
    //    FutureCall infrastructure to lean on). Runs hourly — matches
    //    the notify-window sizing baked into
    //    SupportTicketSlaSweepService.sweepOnce's dedupe logic (see that
    //    file's header) — changing this interval without also revisiting
    //    that window would break the "notified exactly once" guarantee.
    final ticketSlaSweep = getIt<SupportTicketSlaSweepService>();
    Log.startupInfo('Running initial support ticket SLA sweep...');
    final breachedNow = await ticketSlaSweep.sweepOnce();
    Log.startupSuccess('Support ticket SLA sweep complete — $breachedNow breach notification(s) sent');
    Timer.periodic(const Duration(hours: 1), (_) async {
      try {
        final breached = await ticketSlaSweep.sweepOnce();
        if (breached > 0) Log.info('Support ticket SLA sweep: $breached breach notification(s) sent');
      } catch (e) {
        Log.error('Support ticket SLA sweep failed', error: e);
      }
    });

    // 7. Task #132 / Phase 8b — birthday/anniversary campaign sweep.
    //    Daily, not hourly — a birthday only needs day-granularity
    //    detection, unlike an SLA deadline or a trial window (same
    //    "match the interval to what the feature actually needs"
    //    reasoning as the 24h channel health check above). Runs once
    //    immediately so a birthday that lands while the server happened
    //    to be down still gets caught later the same day, then daily.
    final customerCampaignSweep = getIt<CustomerCampaignSweepService>();
    Log.startupInfo('Running initial customer campaign sweep...');
    final greetedNow = await customerCampaignSweep.sweepOnce();
    Log.startupSuccess('Customer campaign sweep complete — $greetedNow greeting(s) sent');
    Timer.periodic(const Duration(hours: 24), (_) async {
      try {
        final greeted = await customerCampaignSweep.sweepOnce();
        if (greeted > 0) Log.info('Customer campaign sweep: $greeted greeting(s) sent');
      } catch (e) {
        Log.error('Customer campaign sweep failed', error: e);
      }
    });
  } catch (e, stackTrace) {
    Log.startupError('Fatal error starting Kola server', error: e);
    Log.error('Initialization crash', error: e, stackTrace: stackTrace);
    rethrow;
  }
}
